### PR TITLE
Changing the order of copy and iNSERT

### PR DESCRIPTION
**Pull request by vibhorkum**
Changing the order of copy and iNSERT for mongoDB and PostgreSQL

### CODE REVIEW

**Comment by vibhorkum** [comment]
Please merge this change in pg_nosql_benchmark

**Comment by gurjeet** [comment]
Can you please explain, possibly in the commit message or a file named changelog, why these changes are necessary? We need to explain it to users of this repository because

a. this is a non-trivial change
b. this change is being applied to stable version 1.0
c. this may invalidate the results generated by the previous, stable version of the script

Because of the above reasons, I feel a change in version number is also called for.

**Comment by vibhorkum** [comment]
This is an important change. Since there were some inserts failing at mongodb due to limitation of mongo client limitation of 4k INSERT size.

It will not invalidate the SELECT, COPY/MONGOIMPORT results. Only INSERTs benchmark of MongoDB will be affected. After this change Benchmark result will show same number of inserts in MongoDB is slower than PostgreSQL.

**Comment by gurjeet** [comment]
Because it affects at least one aspect of any previously generated and/or published results, I strongly feel that it calls for a version number change. Please add another commit to this pull request that also increments the version number according to the rules of Semantic Versioning 2.0.0 (semver.org).

PS: I am curious why you are unable to commit to the repository yourself; given that you are a member of a team in the EnterpriseDB account, you must have the requisite permissions to push to the repository yourself. Let me know, off-thread, if you want to investigate.

**Pull request merged**
